
@startuml

component core {
	package core.core
	package core.io
	package core.io.internal
}

component jackson {
}

component ReportAggregator{

}

component ui {
	package ui.ui
	package ui.ui.controllers
}

component javafx {
    component fxml{
    }
}

component rest {
    package rest.rest
}

component springboot{
}

core.io ..> core.io.internal
core.io ..> jackson
core.io.internal ..> jackson

ui.ui ..> ui.ui.controllers
ui.ui.controllers ..> core.core
ui.ui.controllers ..> core.io

ui ..> javafx
ui ..> fxml
ui.ui.controllers ..> rest
ui.ui ..> rest.rest
ui.ui --> core.io
ui.ui --> core.core

rest.rest ..> core
rest.rest ..> springboot


@enduml
