
@startuml

component core {
	package core.core
	package core.io
	package core.io.internal
}

core.io ..> core.io.internal
core.io ..> jackson
core.io.internal ..> jackson

component jackson {
}




component ui {
	package ui.ui
	package ui.ui.controllers
}

ui.ui ..> ui.ui.controllers
ui.ui.controllers ..> core.core
ui.ui.controllers ..> core.io

component javafx {
    component fxml{
    }
}


ui ..> javafx
ui ..> fxml






@enduml
